name: "Build directory file"
description: "Builds a DIRECTORY.md file with all the algorithms in one repository."
author: "TheAlgorithms"
inputs:
  language:
    description: The language used in your repository
    required: true
  working-directory:
    description: Working/base directory of the script
    required: true
    default: .
  filetypes:
    description: Allowed filenames to check in (comma separated values in a string). Can have unlimited filetypes. E.g. `.cpp,.hpp,.h`
    required: true
  ignored-directories:
    description: Files or folders to ignore, separated by commas.
    required: false
  ignore-folders-children:
    description: Folders to ignore, but include children.
    required: false
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # or whatever version you support
    - name: Running the formatter
      shell: bash
      run: |
        python build_directory_md.py ${{ inputs.language }} ${{ inputs.working-directory }} ${{ inputs.filetypes }} ${{ inputs.ignored-directories }} ${{ inputs.ignore-folders-children }} > DIRECTORY.md

        git pull || true
    - name: Committing and pushing changes
      uses: stefanzweifel/git-auto-commit-action@v4
      id: commit-push
      with:
        commit_message: "docs: updating `DIRECTORY.md`"
        branch: "directory-${{ github.sha }}"
        create_branch: true
    - name: Creating and merging the PR
      shell: bash
      if: steps.commit-push.outputs.changes_detected == 'true'
      run: |
        gh pr create --base ${GITHUB_REF##*/} --head directory-${{ github.sha }} --title 'docs: updating `DIRECTORY.md`' --body '`DIRECTORY.md` has been updated (see the diff. for changes).'
        gh pr merge --admin --merge --subject 'docs: updating `DIRECTORY.md`' --delete-branch
      env:
        GH_TOKEN: ${{ github.token }}
