name: "Filename Formatter"
description: "Format filenames into the acceptable format by TheAlgorithms opganization"
author: "TheAlgorithms"
inputs:
  filetypes:
    description: Filter files by specified file types (comma separated values in a string.) Maximum two values. E.g. `.cpp,.hpp`
    required: true
  working-directory:
    description: Working/base directory of the formatter
    required: false
    default: .
  ignore-files:
    description: Files/folders to ignored
    required: false
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Running the formatter
      shell: bash
      run: |
        ./filename_formatter.sh ${{ inputs.working-directory }} ${{ inputs.filetypes }} ${{ inputs.ignore-files }}

        git pull || true
        git checkout ${ GITHUB_REF_NAME }
    - name: Committing and pushing changes
      id: commit-push
      uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit-message: "chore: formatting filenames"
          branch: file_formatting
          create_branch: true
    - name: Creating and merging the PR
      shell: bash
      if: steps.commit-push.outputs.changes_detected == 'true'
      run: |
        gh pr create --base ${GITHUB_REF##*/} --head file_formatting --title 'chore: formatting filenames' --body 'Formatted filenames (see the diff. for changes).'
        gh pr merge --admin --merge --subject 'chore: formatting filenames' --delete-branch
      env:
        GH_TOKEN: ${{ github.token }}
