name: "Filename Formatter"
description: "Format filenames into the acceptable format by TheAlgorithms opganization"
author: "TheAlgorithms"
inputs:
  filetypes:
    description: Filter files by specified file types (comma separated values in a string.) Maximum two values. E.g. `.cpp,.hpp`
    required: true
  working-directory:
    description: Working/base directory of the formatter
    required: false
    default: .
  ignore-files:
    description: Files/folders to ignored
    required: false
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Setup Git configurations
      shell: bash
      run: |
        git config --global user.name github-actions[bot]
        git config --global user.email 'github-actions@users.noreply.github.com'

        git pull || true
        git checkout -b file_formatting
    - name: Running the formatter
      id: formatter
      shell: bash
      run: |
        ./filename_formatter.sh ${{ inputs.working-directory }} ${{ inputs.filetypes }} ${{ inputs.ignore-files }}
    - name: Committing changes
      if: steps.formatter.outputs.changes_detected == 'true'
      shell: bash
      run: |
        git add ${{ inputs.working-directory }} || true
        git commit -m "chore: formatting filenames" || true

        git push origin file_formatting || true
        gh pr create --base ${GITHUB_REF##*/} --head file_formatting --title 'chore: formatting filenames' --body 'Formatted filenames (see the diff. for changes).'
      env:
        GH_TOKEN: ${{ github.token }}
